# DDPG Configuration
agent:
  actor_lr: 0.0001
  critic_lr: 0.001
  gamma: 0.99
  tau: 0.005  # Polyak averaging parameter
  noise_sigma: 0.2
  noise_decay: 0.995
  buffer_size: 100000
  batch_size: 64

training:
  episodes: 300
  max_steps_per_episode: 200
  save_freq: 50
  eval_freq: 10
  eval_episodes: 5
  warmup_steps: 1000  # Random actions before training

environment:
  name: "Pendulum-v1"
  seed: 42