# DQN Configuration
agent:
  learning_rate: 0.001
  gamma: 0.99
  epsilon: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  buffer_size: 100000
  batch_size: 64
  target_update_freq: 100

training:
  episodes: 500
  max_steps_per_episode: 500
  save_freq: 50
  eval_freq: 10
  eval_episodes: 5

environment:
  name: "CartPole-v1"
  seed: 42