# Quick Experiment Configuration for Testing
# Reduced episodes for faster execution

dqn:
  agent:
    learning_rate: 0.001
    gamma: 0.99
    epsilon: 1.0
    epsilon_min: 0.01
    epsilon_decay: 0.995
    buffer_size: 10000
    batch_size: 32
    target_update_freq: 50
  
  training:
    episodes: 100  # Reduced from 500
    max_steps_per_episode: 200  # Reduced from 500
    save_freq: 25
    eval_freq: 10
    eval_episodes: 3
  
  environment:
    name: "CartPole-v1"
    seed: 42

ddpg:
  agent:
    actor_lr: 0.001
    critic_lr: 0.001
    gamma: 0.99
    tau: 0.005
    buffer_size: 10000
    batch_size: 32
    noise_std: 0.1
    noise_decay: 0.999
  
  training:
    episodes: 100  # Reduced from 400
    max_steps_per_episode: 200  # Reduced
    save_freq: 25
    eval_freq: 10
    eval_episodes: 3
  
  environment:
    name: "Pendulum-v1"
    seed: 42